global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using AutoMapper;
global using VMix.CQRS.Contracts;
global using VMix.Data.Entities;
global using VMix.Mapper.Profiles;