global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using AutoMapper;
global using Verimix.CQRS.Contracts;
global using Verimix.Data.Entities;
global using Verimix.Mapper.Profiles;